_target_: egomimic.scripts.evaluation.blind_eval.BlindEval
eval_path: ${eval_path}
blind_eval_name: 'test1'
models:
  model1:
    _target_: egomimic.scripts.evaluation.video_eval.VideoEval
    eval_path: ${eval_path}
    ckpt_path: ${ckpt_path}
    embodiment_name: "eve_bimanual"
    display_arm: "both"
    cartesian: true
  model2:
    _target_: egomimic.scripts.evaluation.video_eval.VideoEval
    eval_path: ${eval_path}
    ckpt_path: ${ckpt_path}
    embodiment_name: "eve_bimanual"
    display_arm: "both"
    cartesian: true
  