_target_: egomimic.scripts.evaluation.eve_eval.EveEval
eval_path: ${eval_path}
ckpt_path: ${ckpt_path}
embodiment_name: "eve_bimanual"
display_arm: "both"
query_frequency: 50
num_rollouts: 50
debug: ${debug}
cartesian: true