defaults:
  - model: hpt_cotrain_flow_transformer
  - paths: default
  - trainer: ddp
  - debug: null
  - logger: wandb
  - data: ucsd_oboo_cotrain
  - callbacks: null
  - override hydra/launcher: submitit
  - _self_

name: hpt_cotrain_flow_transformer
description: test
ckpt_path: null
train: true
eval: false

eval_class:
  _target_ : egomimic.scripts.evaluation.Eve
  mode: real
  arm: both
  eval_path: "./logs/eval/${name}_${now:%Y-%m-%d_%H-%M-%S}"

hydra:
  run:
    # Dir should be experiment_name/description_{timestamp}
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}

launch_params:
  gpus_per_node: 1
  nodes: 1

data_schematic: # Dynamically fill in these shapes from the dataset
  _target_: rldb.utils.DataSchematic
  norm_mode: minmax
  schematic_dict:
    aria_bimanual:
      front_img_1:
        key_type: camera_keys
        lerobot_key: observations.images.front_img_1
      hp_human_states:
        key_type: proprio_keys
        lerobot_key: observations.state.hp_human_states
      actions_hp_human_actions:
        key_type: action_keys
        lerobot_key: actions_hp_human_actions
      embodiment:
        key_type: metadata_keys
        lerobot_key: metadata.embodiment
    ucsd_h1_bimanual:
      front_img_1:
        key_type: camera_keys
        lerobot_key: observations.images.front_img_1
      front_img_2:
        key_type: camera_keys
        lerobot_key: observations.images.front_img_2
      hp_human_states:
        key_type: proprio_keys
        lerobot_key: observations.state.hp_human_states
      actions_hp_human_actions:
        key_type: action_keys
        lerobot_key: actions_hp_human_actions
      embodiment:
        key_type: metadata_keys
        lerobot_key: metadata.embodiment

  viz_img_key:
    aria_bimanual:
      front_img_1
    ucsd_h1_bimanual:
      front_img_1
